language: rust

env:
  # - TASK=build
  - TASK=test

matrix:
  include:
    - rust: nightly
    - rust: stable
      name: clippy-lint
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy -- -D warnings
    - rust: beta
    - rust: stable
    - rust: 1.32.0
    - rust: nightly
      name: minimal-versions
      script:
        - cargo -Z minimal-versions test --verbose
  exclude:
    - rust: nightly
      env: TASK=build
    - rust: beta
      env: TASK=build
    - rust: stable
      env: TASK=build
    # - rust: 1.23.0
    #   env: TASK=test

script:
  - cargo $TASK --verbose
  - cargo $TASK --no-default-features --features no_logging --verbose
  - cargo $TASK --no-default-features --features dir_source --verbose
