language: rust
rust:
  - nightly
  - beta
  - stable
  - 1.31.0

env:
  # - TASK=build
  - TASK=test

matrix:
  exclude:
    - rust: nightly
      env: TASK=build
    - rust: beta
      env: TASK=build
    - rust: stable
      env: TASK=build
    # - rust: 1.23.0
    #   env: TASK=test

script:
  - cargo $TASK --verbose
  - cargo $TASK --no-default-features --features no_logging --verbose
  - cargo $TASK --no-default-features --features no_dir_source --verbose
